# Конфигурация кулдаунов команд
# Время указывается в секундах

cooldowns:
  fix: 43200        # 12 часов
  'tpa ': 5         # 5 секунд
  lightning: 604800 # 7 дней
  ext: 60           # 1 минута
  'pay ': 15        # 15 секунд
  'broadcast ': 300 # 5 минут